Repository siberiacancode/mock-config-server, pull requests merged in 2023-12, with the labels that each got.

#130 #128 into release@3.3.0 🐘 fix api level interceptors behavior
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
  src/core/middlewares/requestInterceptorMiddleware/requestInterceptorMiddleware.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/server/createDatabaseMockServer/createDatabaseMockServer.ts
  src/server/createGraphQLMockServer/createGraphQLMockServer.ts
  src/server/createMockServer/createMockServer.ts
  src/server/createRestMockServer/createRestMockServer.ts
  src/server/index.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/types/interceptors.ts
Labels: bug

#93 #92 into release@3.3.0 ☄ graphql api examples
  examples/graphql-api/base-url/api-layer.ts
  examples/graphql-api/base-url/server-layer.ts
  examples/graphql-api/mutation/operationName-regex.ts
  examples/graphql-api/mutation/operationName-string.ts
  examples/graphql-api/query/operationName-regex.ts
  examples/graphql-api/query/operationName-string.ts
  tsconfig.dev.json
Labels: documentation

#121 #120 into release@3.3.0 ☄ polling support for rest and graphql
  .eslintrc.js
  bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
  bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
  bin/validateMockServerConfig/validateQueue/validateQueue.test.ts
  bin/validateMockServerConfig/validateQueue/validateQueue.ts
  bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
  bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
  bin/validateMockServerConfig/validateSettings/validateSettings.test.ts
  bin/validateMockServerConfig/validateSettings/validateSettings.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/utils/types/graphql.ts
  src/utils/types/rest.ts
Labels: enhancement

#135 #120 into release@3.3.0 ☄ readme polling
  README.md
Labels: documentation
