Repository siberiacancode/mock-config-server, pull requests merged in 2023-05, with the labels that each got.

#40 #36 into release@2.2.0 ☄️ add async await for callResponseInterceptors (setDelay case)
  README.md
  bin/bin.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/helpers/sleep.ts
  src/utils/types/interceptors.ts
Labels: bug

#42 #38 into release@2.2.0 ☄️ add LICENSE and Security policy
  LICENSE
  SECURITE.md
  package.json
Labels: documentation

#48 #47 into release@2.2.0👹 add cli option 'config': absolute or relative path to config
  README.md
  bin/cli.ts
  bin/resolveConfigFilePath/resolveConfigFilePath.ts
  bin/start.ts
  src/utils/types/server.ts
Labels: enhancement

#50 #49 into release@2.2.0 ☄️ rework request interceptor
  README.md
  SECURITY.md
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
  src/core/middlewares/corsMiddleware/corsMiddleware.ts
  src/core/middlewares/index.ts
  src/core/middlewares/noCorsMiddleware/noCorsMiddleware.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
  src/core/middlewares/requestInterceptorMiddleware/requestInterceptorMiddleware.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/server/createMockServer/createMockServer.ts
  src/utils/helpers/index.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptors.test.ts
  src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.test.ts
  src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/helpers/interceptors/helpers/setDelay.ts
  src/utils/helpers/interceptors/index.ts
  src/utils/helpers/parseCookie/parseCookie.test.ts
  src/utils/helpers/parseCookie/parseCookie.ts
  src/utils/types/interceptors.ts
Labels: bug

#52 #51 into release@2.2.0 🐘 fix npx script in README
  README.md
Labels: bug

#45 #43 into release@2.2.0 🐘 watch mode for restart server on files change
  .eslintrc
  .gitignore
  README.md
  bin/build.ts
  bin/cli.ts
  bin/helpers/index.ts
  bin/helpers/resolveConfigFile.ts
  bin/helpers/resolveConfigFilePath.ts
  bin/helpers/resolveExportsFromSourceCode.ts
  bin/run.ts
  bin/start.ts
  package.json
  src/core/middlewares/destroyerMiddleware/destroyerMiddleware.ts
  src/core/middlewares/index.ts
  src/server/index.ts
  src/server/startMockServer/startMockServer.ts
  src/utils/types/server.ts
  tsconfig.dev.json
Labels: enhancement

#58 #57 into release@2.3.0 🐘 add cookies support
  README.md
  bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
  bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
  bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
  bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
  jest.config.js
  src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.ts
  src/core/middlewares/cookieParseMiddleware/cookieParseMiddleware.test.ts
  src/core/middlewares/cookieParseMiddleware/cookieParseMiddleware.ts
  src/core/middlewares/index.ts
  src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
  src/server/createMockServer/createMockServer.ts
  src/utils/helpers/parseCookie/parseCookie.ts
  src/utils/types/graphql.ts
  src/utils/types/rest.ts
  src/utils/types/values.ts
Labels: enhancement

#60 #56 into release@2.3.0 ☄ add get header and headers and get cookie func for responce int…
  README.md
  src/core/middlewares/cookieParseMiddleware/cookieParseMiddleware.ts
  src/core/middlewares/cookieParseMiddleware/helpers/index.ts
  src/core/middlewares/cookieParseMiddleware/helpers/parseCookie/parseCookie.test.ts
  src/core/middlewares/cookieParseMiddleware/helpers/parseCookie/parseCookie.ts
  src/utils/helpers/index.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/types/interceptors.ts
Labels: documentation, enhancement
