Repository siberiacancode/mock-config-server, pull requests merged in 2025-01, with the labels that each got.

#131 #102 into release@3.7.0 🐘 add logger support
  .eslintrc.js
  README.md
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
  src/core/middlewares/contextMiddleware/contextMiddleware.ts
  src/core/middlewares/cookieParseMiddleware/helpers/parseCookie/parseCookie.ts
  src/core/middlewares/index.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/server/createDatabaseMockServer/createDatabaseMockServer.ts
  src/server/createGraphQLMockServer/createGraphQLMockServer.ts
  src/server/createMockServer/createMockServer.ts
  src/server/createRestMockServer/createRestMockServer.ts
  src/server/startDatabaseMockServer/startDatabaseMockServer.ts
  src/server/startGraphQLMockServer/startGraphQLMockServer.ts
  src/server/startMockServer/startMockServer.ts
  src/server/startRestMockServer/startRestMockServer.ts
  src/static/views/pages/404/index.ejs
  src/utils/helpers/date/formatTimestamp/formatTimestamp.test.ts
  src/utils/helpers/date/formatTimestamp/formatTimestamp.ts
  src/utils/helpers/date/index.ts
  src/utils/helpers/index.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.test.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/helpers/logger/callRequestLogger/callRequestLogger.test.ts
  src/utils/helpers/logger/callRequestLogger/callRequestLogger.ts
  src/utils/helpers/logger/callResponseLogger/callResponseLogger.test.ts
  src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
  src/utils/helpers/logger/helpers/filterTokens/filterTokens.test.ts
  src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
  src/utils/helpers/logger/helpers/formatTokens/formatTokens.test.ts
  src/utils/helpers/logger/helpers/formatTokens/formatTokens.ts
  src/utils/helpers/logger/helpers/index.ts
  src/utils/helpers/logger/index.ts
  src/utils/types/checkModes.ts
  src/utils/types/graphql.ts
  src/utils/types/index.ts
  src/utils/types/interceptors.ts
  src/utils/types/logger.ts
  src/utils/types/rest.ts
  src/utils/types/server.ts
  src/utils/types/shared.ts
  src/utils/types/values.ts
Labels: enhancement

#201 #158 into release@4.0.0 🐘 add file polling support
  README.md
  bin/validateMockServerConfig/queueSchema/queueSchema.ts
  src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
  src/core/middlewares/errorMiddleware/errorMiddleware.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  src/utils/helpers/files/index.ts
  src/utils/helpers/files/isFileDescriptor/isFileDescriptor.ts
  src/utils/types/files.ts
  src/utils/types/graphql.ts
  src/utils/types/index.ts
  src/utils/types/rest.ts
Labels: enhancement, release@4.0.0

#205 #204 into release@3.7.1 🐘 fix error throw on non GET/POST requests
  src/core/middlewares/contextMiddleware/contextMiddleware.ts
Labels: bug

#208 #204 into release@3.7.1 🐘 do not parse graphql query if method not GET or POST in notFoundMiddleware
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
Labels: bug

#199 #195 into release@4.0.0 👹 upgrade body-parser to v2 + no more specific handling for empty object body
  package.json
  src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
  src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
  yarn.lock
Labels: invalid, release@4.0.0

#194 #106-deleted into #187 🧊 delete ejs, delete not found middleware
  package.json
  src/core/middlewares/index.ts
  src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
  src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.ts
  src/core/middlewares/notFoundMiddleware/helpers/getLevenshteinDistance/getLevenshteinDistance.test.ts
  src/core/middlewares/notFoundMiddleware/helpers/getLevenshteinDistance/getLevenshteinDistance.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/helpers/getActualRestUrlMeaningfulString/getActualRestUrlMeaningfulString.test.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/helpers/getActualRestUrlMeaningfulString/getActualRestUrlMeaningfulString.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/helpers/getPatternRestUrlMeaningfulString/getPatternRestUrlMeaningfulString.test.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/helpers/getPatternRestUrlMeaningfulString/getPatternRestUrlMeaningfulString.ts
  src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/helpers/index.ts
  src/core/middlewares/notFoundMiddleware/helpers/index.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
  src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
  src/server/createDatabaseMockServer/createDatabaseMockServer.ts
  src/server/createFlatMockServer/createFlatMockServer.ts
  src/server/createGraphQLMockServer/createGraphQLMockServer.ts
  src/server/createMockServer/createMockServer.ts
  src/server/createRestMockServer/createRestMockServer.ts
  src/static/views/assets/icons/scheme-dark.svg
  src/static/views/assets/icons/scheme-light.svg
  src/static/views/assets/images/404.png
  src/static/views/assets/images/logo.png
  src/static/views/assets/styles/global.css
  src/static/views/components/header/index.css
  src/static/views/components/header/index.ejs
  src/static/views/components/header/index.js
  src/static/views/features/scheme/dark.css
  src/static/views/features/scheme/index.ejs
  src/static/views/features/scheme/index.js
  src/static/views/features/scheme/light.css
  src/static/views/features/tab/index.css
  src/static/views/features/tab/index.ejs
  src/static/views/features/tab/index.js
  src/static/views/pages/404/index.css
  src/static/views/pages/404/index.ejs
  yarn.lock
Labels: invalid, release@4.0.0

#193 #192 into #187 🧊 add validate to create functions
  .swcrc
  bin/helpers/index.ts
  bin/init.ts
  bin/run.ts
  bin/runFlatConfig.ts
  src/server/createFlatMockServer/createFlatMockServer.ts
  src/server/createGraphQLMockServer/createGraphQLMockServer.ts
  src/server/createMockServer/createMockServer.ts
  src/server/createRestMockServer/createRestMockServer.ts
  src/server/startFlatMockServer/startFlatMockServer.ts
  src/utils/validate/baseUrlSchema/baseUrlSchema.ts
  src/utils/validate/corsSchema/corsSchema.ts
  src/utils/validate/databaseConfigSchema/databaseConfigSchema.ts
  src/utils/validate/getMostSpecificPathFromError.ts
  src/utils/validate/getValidationMessageFromPath.ts
  src/utils/validate/graphqlConfigSchema/graphqlConfigSchema.ts
  src/utils/validate/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
  src/utils/validate/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
  src/utils/validate/index.ts
  src/utils/validate/interceptorsSchema/interceptorsSchema.ts
  src/utils/validate/isOnlyRequestedDataResolvingPropertyExists.ts
  src/utils/validate/portSchema/portSchema.ts
  src/utils/validate/queueSchema/queueSchema.ts
  src/utils/validate/restConfigSchema/restConfigSchema.ts
  src/utils/validate/restConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
  src/utils/validate/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
  src/utils/validate/settingsSchema/settingsSchema.ts
  src/utils/validate/staticPathSchema/staticPathSchema.ts
  src/utils/validate/utils/checkModeSchema/checkModeSchema.ts
  src/utils/validate/utils/entitiesSchema/entitiesSchema.test.ts
  src/utils/validate/utils/entitiesSchema/entitiesSchema.ts
  src/utils/validate/utils/index.ts
  src/utils/validate/utils/jsonSchema/jsonSchema.ts
  src/utils/validate/utils/plainObjectSchema/plainObjectSchema.ts
  src/utils/validate/utils/requiredPropertiesSchema/requiredPropertiesSchema.ts
  src/utils/validate/utils/sharedSchema/sharedSchema.ts
  src/utils/validate/validateApiMockServerConfig.ts
  src/utils/validate/validateFlatMockServerConfig.ts
  src/utils/validate/validateMockServerConfig.ts
  tsconfig.dev.json
  tsconfig.production.json
Labels: enhancement, release@4.0.0

#171 #151 into release@4.0.0 🧊 add orm in interceptor
  .eslintrc.js
  bin/validateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
  bin/validateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
  package.json
  src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
  src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
  src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
  src/core/database/createOrm/createOrm.test.ts
  src/core/database/createOrm/createOrm.ts
  src/core/database/createStorage/createStorage.ts
  src/core/database/index.ts
  src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
  src/core/middlewares/contextMiddleware/contextMiddleware.ts
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/server/createDatabaseMockServer/createDatabaseMockServer.ts
  src/server/createGraphQLMockServer/createGraphQLMockServer.ts
  src/server/createMockServer/createMockServer.ts
  src/server/createRestMockServer/createRestMockServer.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.test.ts
  src/utils/helpers/interceptors/callRequestInterceptor/callRequestInterceptor.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
  src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.ts
  src/utils/types/database.ts
  src/utils/types/interceptors.ts
  src/utils/types/server.ts
Labels: enhancement, release@4.0.0

#213 technical/fix-content-disposition-header-on-windows into release@4.0.0 🐘 fix content-disposition header setting with windows-like path
  src/core/rest/createRestRoutes/createRestRoutes.test.ts
  src/core/rest/createRestRoutes/createRestRoutes.ts
Labels: bug

#217 #216 into release@4.0.1 🐘 fix crush on sending empty body
  src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
Labels: bug

#228 #225 into release@4.0.3 🧊 return default value for port
  src/server/startFlatMockServer/startFlatMockServer.ts
Labels: bug
